### ISSUE TITLE
Combining the output of different types of queries in the same table

### ISSUE THREAD

**Issue by xiangsheng** [SqrtMinusOne/biome#4]
Is it possible show the output of different types of queries, say weather forecast and air quality, of the same city in a same table? It will be very convenient. For the same reason, can the `biome-def-preset` set the weather forecast and the air quality parameter at the same time?

**Comment by SqrtMinusOne** [comment]
Technically it should be possible to implement. Will try when I have the time.

**Comment by SqrtMinusOne** [comment]
Added in #5. `M-x biome-multi` invokes the multi-query dialog.

It's a bit more complicated than I'd like, but seems to work.

**Comment by xiangsheng** [comment]
Works well! Thank you.
