### ISSUE TITLE
Feature Request: turn off unit/parameter display in column headers

### ISSUE THREAD

**Issue by TitusMu** [SqrtMinusOne/biome#6]
First: I upgraded to Emacs 30.0.50 yesterday, and to my delight Biome continues to work. I use it every day, because I go by bike everywhere and need to know the weather coming up in the next hours. Thank you so much for bringing it to Emacs! It has helped me for many months now.

Would it be hard to make it possible to turn off the display of units/parameters in the column headers? It would be great to have this option, so it doesn't say "iso8601", "°C", "mm" and "wmo code" there anymore.

**Comment by SqrtMinusOne** [comment]
Glad to hear that you find the package useful!

You can turn off the units by:
```lisp
(setq biome-grid-display-units nil)
```

But what's your use case? If you want to display as many columns as possible in one buffer, you may need column names like 1, 2, 3... I can make a [custom format string](https://www.gnu.org/software/emacs/manual/html_node/elisp/Custom-Format-Strings.html) to configure headers, of which I wasn't aware when I wrote this package.

**Comment by TitusMu** [comment]
Ha! Just wonderful! Now I can give it the very clean look I was trying to. Probably too little information for many others, but in my case (always the same city, always the same data) it helps me see at a glance what the next hours will look like. I messed with your biome-grid.el to have the biome-grid-wmo-codes in German, and I turned on hl-line-mode in biome-grid.el to have a better look along the line by hour.
![Screenshot_Biome](https://github.com/SqrtMinusOne/biome/assets/110761073/73dd1efd-87ed-43b3-bcfa-b3cc61e42b54)

Now the last thing I'd love to have is the line marked at the current hour, so I do not have to search for it after opening the biome-preset. I can write a function that does it (with hl-line-mode turned on), but strangely it only works if bound to a key and called by hand. When I add it to my small function that calls the biome-preset, it won't work. Hm, why is that? Do you have an idea?

```
(isearch-forward nil 1)
(isearch-yank-string (format-time-string "%H" (current-time)))
(execute-kbd-macro 'my/hit-C-k)
```

**Comment by SqrtMinusOne** [comment]
I don't think there's a way to do that with `biome-preset`.

I've changed `biome-grid` a bit: https://github.com/SqrtMinusOne/biome/commit/8fae4deec37170792efdc45f103031e617b42a04, so now it should be possible to put the function in `biome-grid-mode-hook`.

I'd do it like this:
```lisp
(defface my/biome-current-hour-face
  '((t :inherit highlight :extend t))
  "Highlight the current hour."
  :group 'biome)

(defun my/biome-highlight-current-hour ()
  (interactive)
  (save-excursion
    (goto-char (point-min))
    (let ((needle (substring
                   (format-time-string biome-grid-datetime-format (current-time))
                   0 -3)))
      (when (search-forward needle nil t)
        (let ((ov (make-overlay (line-beginning-position) (line-end-position))))
          (overlay-put ov 'priority -49)
          (overlay-put ov 'face 'my/biome-current-hour-face))))))

(add-hook 'biome-grid-mode-hook #'my/biome-highlight-current-hour)
```

**Comment by TitusMu** [comment]
Wow! You are unbelievable! I wish I could write elisp as well as you do. Now it is even better than what I tried to do, it looks so neat and I can see the current weather at a glance. Thank you so much for writing this function and hook, I couldn't have done it. And thank you for writing biome in the first place!

**Comment by SqrtMinusOne** [comment]
You're welcome! 

Feel free to re-open the issue if necessary.
